### ISSUE TITLE
pylint improvements

### ISSUE THREAD

**Issue by mrichar1** [colinhiggs/pyramid-jsonapi#108]
We're very close to a perfect 10 score for pylint - it'd be nice to aim for this before releasing 2.x

There are a couple of specific issues, and a few general 'classes' of issues:

```W:1902, 0: TODO(Colin): deal with relationships properly. (fixme)``` - can/should this be fixed for 2.x?

```C:  1, 0: Too many lines in module (2757/1000) (too-many-lines)``` - we talked before about splitting the module into at least a couple of smaller chunks: if we split by class we'd end up with: `PyramidJSONAPI`, `CollectionViewBase`, `DebugView` and FilterRegistry` which seem like suitable places to divide things. I'm happy to do this once the other outstanding PRs/changes are settled. (DRYing CollectionViewBase might also help with this).

```Missing class docstring``` - several docstrings need written - worth doing for 2.0 release.

```Too many branches/local variables/statements/attributes``` - there are a number of these - we should review them all and decide whether they are deliberate design decisions, or the result of growing code. For example, `endpoints` has a number of route-related attributes that might be better stored in a single route_data object.

**Comment by colinhiggs** [comment]
docstrings dealt with in #111

**Comment by mrichar1** [comment]
Overhauled in #129 and #133 - remaining issues probably need more thought, and can be left until post-2.x
