### ISSUE TITLE
problem with version.py

### ISSUE THREAD

**Issue by umeboshi2** [colinhiggs/pyramid-jsonapi#140]
I got this error message.
FileNotFoundError: [Errno 2] No such file or directory: .virtualenvs/pj/lib/python3.5/site-packages/pyramid_jsonapi/../PKG-INFO'

**Comment by colinhiggs** [comment]
2.0.2 (now pushed to pypi) should fix the issue for pip. Please let us know if that is not the case.

**Comment by umeboshi2** [comment]
It's working now.  Thanks.  :)
