### ISSUE TITLE
pserve fails to start due to conflicting notfound views

### ISSUE THREAD

**Issue by vanguard737** [colinhiggs/pyramid-jsonapi#151]
After installing pyramid_jsonapi (2.1.5) and configuring it for an existing Pyramid (1.9.1) project, pserve fails to start with the following errors:

```
pyramid.exceptions.ConfigurationConflictError: Conflicting configuration actions
  For: ('view', <class 'pyramid.httpexceptions.HTTPNotFound'>, '', None, 'd41d8cd98f00b204e9800998ecf8427e')
    Line 129 of file c:\users\cjbro\dropbox\workspace\poolshark\env\lib\site-packages\pyramid_jsonapi\__init__.py:
        self.config.add_notfound_view(self.error, renderer='json')
    Line 4 of file c:\users\cjbro\dropbox\workspace\poolshark\poolshark\views\notfound.py:
        @notfound_view_config(renderer='../templates/404.jinja2', append_slash=True)
```

Looks like pyramid_jsonapi is (quite sensibly) adding a notfound_view for itself.  This unfortunately collides with my application's pre-existing notfound view definition, which displays a human-user-friendly 404 page (as well as handling redirects to slash-appended routes:  [https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/urldispatch.html]).

As a workaround, I updated my @notfound_view_config with a path_info regex.

Me, before:
`@notfound_view_config(renderer='../templates/404.jinja2', append_slash=True)`

Me, after:
`@notfound_view_config(path_info="(?!\/api\/)^.*$", renderer='../templates/404.jinja2', append_slash=True)`

Ugly, but seems to work well enough.  This allows the server to start, and sends all notfound requests to my custom page if path_info doesn't begin with /api/ (assuming I haven't botched the regex).  I could (and probably will) extend this to cover /metadata/ as well.

That said:  Would it be reasonable for pyramid_jsonapi to create its notfound_view in a way that's less likely to create such collisions?  Extending the above, I guess pyramid_jsonapi's add_notfound_view call could fashion its own path_info from the route_pattern_prefix, route_pattern_api_prefix, and route_pattern_metadata_prefix settings.  (Alternatively, if there's no safe/reasonable way to do this, maybe just a note in the documentation would help.)

If the above isn't clear, just let me know - happy to provide more info if necessary.

**Comment by colinhiggs** [comment]
Seems clear enough. I suggest that pyramid-jsonapi should only create notfound views for the paths that it controls (/api and /metadata by default) as a means of minimising the chance of conflicts. It would seem sensible (and be pretty easy) to add a config file option to disable the notfound view as well, for those who are rolling their own.

I'll get on it (after my many meetings :))

**Comment by colinhiggs** [comment]
First pass at fixing this is in the `notfound` branch. This adds error/notfound/forbidden handlers only for paths that start with `/api/` or `/metadata/` (or whatever prefix strings are specified in the config file). If an empty prefix is specified it will still register handlers for everything starting with '/' (i.e. everything).

I need to write a couple of tests but it seems to work.

**Comment by vanguard737** [comment]
Awesome - much appreciated.  I'll see if I can get some manual testing done against the notfound branch this weekend, in case that helps.

**Comment by vanguard737** [comment]
FYI, built the notfound branch locally, installed the wheel, reverted my notfound-view definition to the non-regex version, successfully started the server, and verified that all 404s are giving the desired result (JSON for calls to /api/* and /metadata/*, my custom HTML for anything else.)  In other words, all's right with the world.  Thanks!
