### ISSUE TITLE
Omitting relationships in the generated API

### ISSUE THREAD

**Issue by lelit** [colinhiggs/pyramid-jsonapi#160]
I want to omit one single entity class from the generated API, and that is simple enough:
```python
    exposed_entities = (cls for cls in models.Base.__subclasses__()
                        if cls is not models.User)
    pjapi = JSONAPI(config, exposed_entities, lambda x: models.DBSession())
```

Most other entities carry an `idowner` foreign key to that table, and have a `owner` relationship with the `User` entities: if I can omit the former putting a `visible=False` on the column, I fail to understand how can omit also the latter. 

Inspecting the code, I see that when the relationships are collected by `collection_view_factory` they are checked against the `expose_fields` argument, but IIUC there's no way to specify that parameter, at least when using the `create_jsonapi()`.

For now I solved with the following customization:
```python
class JSONAPI(PyramidJSONAPI):
    "Customize ``PyramidJSONAPI`` to completely omit `owner` and `idowner` attributes."

    class RestrictedFields:
        def __contains__(self, name):
            return name not in ('owner', 'idowner')

    def collection_view_factory(self, model, collection_name=None, expose_fields=None):
        if expose_fields is None:
            expose_fields = self.RestrictedFields()
        return super().collection_view_factory(model, collection_name, expose_fields)
```

I wonder if I'm missing an easier/recommended way.

Thanks in advance for any hint!

**Comment by mrichar1** [comment]
It turns out that the `visible` option was very easy to extend to relationships, which we believe should allow you to choose to exclude both the field and associated relationships. The test suite has an example of this:

https://github.com/colinhiggs/pyramid-jsonapi/blob/master/test_project/test_project/tests.py#L3009-L3014

Can you let us know if this is enough for the use-case you are envisaging?

**Comment by lelit** [comment]
Sure, thank you! I will report back as soon as I can focus on that again.

**Comment by lelit** [comment]
I tried current master and I confirm that everything works great, thank you!

**Comment by colinhiggs** [comment]
Looks like this has fixed the issue.
