### ISSUE TITLE
Making dependency on PyYaml optional

### ISSUE THREAD

**Issue by lelit** [colinhiggs/pyramid-jsonapi#161]
Currently pyramid-jsonapi have an _hard_ dependency on PyYaml. I wonder if it could be lifted, with the following reasoning:

1. apparently it is only used by the `metadata` feature, but the `OpenAPI` submodule is loaded even when such feature is disabled (that is, with `pyramid_jsonapi.metadata_endpoints = False`)
2. expecially under Python 3.7, one may prefer `ruamel.yaml` because it already comes with binary wheels and, at least up to very recently, more actively maintained

I know that supporting different-but-equivalent packages is a bit boring, as you either must anticipate that with something like
```python
try:
   import foo
except ImportError:
  import bar as foo
```
or provide a way for the end user to choose the implementation for example with
```python
@functools.lru_cache()
def generate_openapi(self, request=None, safe_load=None):
    """Generate openapi documentation."""
    ...
    if safe_load is None:
        from yaml import safe_load
    ...
```

What do you think?

**Comment by mrichar1** [comment]
Thanks for raising this.

In terms of replacing modules, the easiest approach (which doesn't require modifying the underlying module code) is to override sys.modules before the import (e.g. in `__init__.py` in your pyramid project):

```
import sys
from ruamel.yaml import YAML
sys.modules['yaml'] = YAML
```

Then we see:

```
import yaml
help(yaml)
> Help on class YAML in module ruamel.yaml.main:
```

Does this satisfy your needs for drop-in replacement modules?

If we were to look into providing alternative module dependencies, then I think we'd probably want to go down the [`extras_require`](http://peak.telecommunity.com/DevCenter/setuptools#declaring-extras-optional-features-with-their-own-dependencies) route (though this might be overkill here).

**Comment by lelit** [comment]
Yes, that's what I actually did to workaround my buggy test :smiley:
Solved that, the fact that I had to install **also** pyyaml _anyway_ made me think though...
