### ISSUE TITLE
Feature request: Allow JSONB filters

### ISSUE THREAD

**Issue by kenneaal** [colinhiggs/pyramid-jsonapi#36]
Greetings.

At present, there is one limitation I face while deploying pyramid-jsonapi - namely a lack of support for doing filters on jsonb columns. If possible, could a filter entry point for jsonb search operators be made?

**Comment by colinhiggs** [comment]
Just getting back to this after some time away...

Do you mean adding support for some of these operators:

https://www.postgresql.org/docs/current/static/functions-json.html

inside the filter query parameter, like:

filter[colname:>@]='{"a": 1}'

?

With appropriate quoting and/or operator renaming.

Maybe a better way to tackle this would be to figure out a way to allow for extending the filter operators...

**Comment by kenneaal** [comment]
That is the idea, yes. At present it is possible to fake this using contains, but it is not particularly optimized.

-------- Opprinnelig melding --------Fra: Colin Higgs <notifications@github.com> Dato: 30.06.2017  17:52  (GMT+01:00) Til: colinhiggs/pyramid-jsonapi <pyramid-jsonapi@noreply.github.com> Ko: Kenneth Aalberg <kenneaal@gmail.com>, Author <author@noreply.github.com> Emne: Re: [colinhiggs/pyramid-jsonapi] Feature request: Allow JSONB filters (#36) 
Just getting back to this after some time away...
Do you mean adding support for some of these operators:
https://www.postgresql.org/docs/current/static/functions-json.html
inside the filter query parameter, like:
filter[colname:>@]='{"a": 1}'
?
With appropriate quoting and/or operator renaming.
Maybe a better way to tackle this would be to figure out a way to allow for extending the filter operators...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/colinhiggs/pyramid-jsonapi","title":"colinhiggs/pyramid-jsonapi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/colinhiggs/pyramid-jsonapi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@colinhiggs in #36: Just getting back to this after some time away...\r\n\r\nDo you mean adding support for some of these operators:\r\n\r\nhttps://www.postgresql.org/docs/current/static/functions-json.html\r\n\r\ninside the filter query parameter, like:\r\n\r\nfilter[colname:\u003e@]='{\"a\": 1}'\r\n\r\n?\r\n\r\nWith appropriate quoting and/or operator renaming.\r\n\r\nMaybe a better way to tackle this would be to figure out a way to allow for extending the filter operators..."}],"action":{"name":"View Issue","url":"https://github.com/colinhiggs/pyramid-jsonapi/issues/36#issuecomment-312304428"}}}

**Comment by colinhiggs** [comment]
I've just checked in a change that should allow for adding filter operators. Still needs documented but in the meantime have a look at the FilterOperator class. Roughly speaking:

* create new operators as FilterOperator instances (e.g. for '@>' we might call it 'json_contains'):
  `fop = FilterOperator('json_contains', some_func)`
  where `some_func` is a function that takes a sqlalchemy property (attribute or relationship) as an argument and returns a function implementing the filter on that property.

* register the filter operator with the filter operator collection of the api object:
  `js = PyramidJSONAPI(config, models, get_dbsession)`
  ...
  `js.filter_operator_collection.register(fop)`

* Your filter operator should now be recognised:
  `http http://yourhost/api/collection_name?filter[attribute:json_contains]=some_json`

**Comment by colinhiggs** [comment]
Checked in a new way to do it, but it still leaves much to be desired in terms of potential clashes between the needs of different column types. Still working on it.

**Comment by colinhiggs** [comment]
There is now a better mechanism for adding filters to pyramid_jsonapi (see the documentation). The comparators defined for the JSONB type in sqlalchemy have been added.
