### ISSUE TITLE
JSONAPI validation

### ISSUE THREAD

**Issue by mrichar1** [colinhiggs/pyramid-jsonapi#39]
There are a lot of places in the code where the validity of received JSON against the JSONAPI standard is done in an ad-hoc basis - e.g. checking for existence of top-level 'data' key etc.

It might be worth using a validation library to have a schema that defines valid JSONAPI structure and perform a single validation step on all received (and possibly) sent JSON.

There are a few libraries that offer this - my preference would be (in order): [cerberus](http://docs.python-cerberus.org), [voluptuous](http://alecthomas.github.io/voluptuous/docs/_build/html/index.html) or possibly [colander](http://colander.readthedocs.io/en/latest/index.html)

**Comment by colinhiggs** [comment]
Great idea. Given that I would have reached for this approach almost automatically when I was working with xml, I can't believe I didn't code it this way for jsonapi :).

**Comment by mrichar1** [comment]
Added in #40
