### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by mrichar1** [colinhiggs/pyramid-jsonapi#46]
There are several places where raised exceptions try to make use of `op` and `prop` variables - however they don't appear to be defined. It looks like they are defined 'locally' in `query_add_filtering()`, but while this is called, it doesn't pass them back up to the parent method.

https://github.com/colinhiggs/pyramid-jsonapi/blob/master/pyramid_jsonapi/__init__.py#L888

https://github.com/colinhiggs/pyramid-jsonapi/blob/master/pyramid_jsonapi/__init__.py#L1144

https://github.com/colinhiggs/pyramid-jsonapi/blob/master/pyramid_jsonapi/__init__.py#L1245

https://github.com/colinhiggs/pyramid-jsonapi/blob/master/pyramid_jsonapi/__init__.py#L1698

The fact that this hasn't shown up also means that the code path that generates these exceptions aren't being tested.

**Comment by colinhiggs** [comment]
Just done a coverage report for pyramid_jsonapi/__init__.py and it currently sits at 85%. I'll see if I can fix this bug set and increase the coverage a bit before going for a 1.0.0 release.
