### ISSUE TITLE
'Type' name wrong when mapped through a relationship

### ISSUE THREAD

**Issue by mrichar1** [colinhiggs/pyramid-jsonapi#90]
An example test that flags this up:

`http PATCH http://localhost:8888/blogs/1/relationships/owner`

Results in:

`409 Conflict: Resource identifier type 'owner' does not match relationship type 'people'`

This is presumably due to the `test_project` model using a different backref to the class/table name:
```
class Person(Base):
    __tablename__ = 'people'
    blogs = relationship('Blog', backref='owner')
```

This only seems to happen for PATCH, not for POST.

**Comment by colinhiggs** [comment]
What JSON did you send?

That error is saying that the 'type' key in the resource identifier (the JSON that looks like {"type": "something", "id": "something"}) sent in the PATCH request was set to "owner" when it should be "people".

**Comment by mrichar1** [comment]
It appears that what I thought was an error is actually standard (if unpleasant) behaviour in the schema.

I'd assumed that if the endpoint was `.../relationships/owner` then the data should contain `"type": "owner"` but obviously this isn't true - there are examples of e.g. `author -> people` in the jsonapi documentation examples.

I'll close this issue and just mark it down as 'thats a really easy way to confuse your api users' and vow to never do this myself!  :smiley:
